config/routes.rb
Rails.application.routes.draw do
	resources :home
	resources :clients
	resources :products 
  resources :brands
  resources :orders

  get '/entrar' => 'sessions#new'
  post '/entrar' => 'sessions#create'
  get '/sair' => 'sessions#destroy'
  
  get '/cadastrar' => 'users#new'
  post '/users' => 'users#create'

  root 'sessions#new'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
  has_many :orders
  
  validates :name , presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
	validates :name, presence: true
	validates :address, presence: true
	validates :tel, presence: true
	validate :cpf
	validate :rg
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :product

	validates :date, presence: true
	validates :quantity, presence: true
	validates :value, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  has_many :order
  
	validates :name, presence: true
	validates :quantity, presence: true
	validates :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/entrar' unless current_user
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
#before_filter :authorize

  def index
    @brands = Brand.all
    respond_to do |format|
      format.html
      format.json { render json: @brands }
    end
  end

  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @brand }
    end
  end

  def new
    @brand = Brand.new
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      respond_to do |format|
        format.html { redirect_to @brand }
        format.json { render json: @brand, status: :created }
      end
    else
      render 'new'
    end
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      respond_to do |format|
        format.html { redirect_to @brand }
        format.json { render json: @brand, status: :created }
      end
    else
      render 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand = Brand.destroy(params[:id])
      respond_to do |format|
        format.html { redirect_to brands_path }
        format.json { render json: @brand, status: :created }
      end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
#before_filter :authorize

  def index
    @clients = Client.all
    respond_to do |format|
      format.html
      format.json { render json: @clients }
    end
  end

  def show
    @client = Client.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      respond_to do |format|
        format.html { redirect_to @client }
        format.json { render json: @client, status: :created }
      end
    else
      render 'new'
    end
  end

  def update
  	@client = Client.find(params[:id])
    if @client.update(client_params)
      respond_to do |format|
        format.html { redirect_to @client }
        format.json { render json: @client, status: :created }
      end
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client = Client.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to clients_path }
      format.json { render json: @client, status: :created }
    end
  end

  private

  def client_params
    params.require(:client).permit(:name, :address, :tel, :cpf, :rg)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
    @orders = Order.all
    respond_to do |format|
      format.html
      format.json { render json: @orders }
      format.xlsx { render xlsx: 'index'}
    end
  end

  def show
    @order = Order.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @order }
    end
  end

  def new
    @order = Order.new
    @product = Product.new
  end

  def create
    @order = Order.new(order_params)
    @order.product = Product.find_by_id(params['produto'])
    if @order.save
      respond_to do |format|
        format.html { redirect_to @order }
        format.json { render json: @order, status: :created }
      end
    else
      render 'new'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order = Order.destroy(params[:id])
      respond_to do |format|
        format.html { redirect_to orders_path }
        format.json { render json: @order, status: :created }
      end
  end

  private

  def order_params
    params.require(:order).permit(:data, :quantity, :value)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#before_filter :authorize
  
  def index  
    @products = Product.all
    respond_to do |format|
      format.html
      format.json { render json: @products }
    end 
  end

  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new
    @brand = Brand.new
  end

  def edit
    @product = Product.find(params[:id])
    @brands = Brand.all
  end

  def create
    @product = Product.new(product_params)
    @product.brand = Brand.find_by_id(params['marca'])
    if @product.save
      respond_to do |format|
        format.html { redirect_to @product }
        format.json { render json: @product, status: :created }
      end
    else
      render 'new'
    end
  end

  def update
  	@product = Product.find(params[:id])
    @product.brand = Brand.find_by_id(params['brands'])
    if @product.update(product_params)
      respond_to do |format|
        format.html { redirect_to @product }
        format.json { render json: @product, status: :created }
      end
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product = Product.destroy(params[:id])
      respond_to do |format|
        format.html { redirect_to products_path }
        format.json { render json: @product, status: :created }
      end
  end

  private

  def product_params
    params.require(:product).permit(:name, :quantity, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to home_index_path
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/entrar'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/entrar'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to home_index_path
    else
      redirect_to '/cadastrar'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/edit.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-edit"> 
  Editar Marca </span></h1>
  <%= form_for :brand, url: brand_path(@brand), method: :patch do |f| %>
    <% if @brand.errors.any? %>
      <div class= "alert alert-danger" id="error_explanation">
        <ul>
          <h2>
            Ops!
          </h2>
          <% @brand.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-md-12">  
        <%= f.label 'Nome' %><br>
        <div class="col-md-4">
          <%= f.text_field :name , class: 'form-control'%>
        </div>
      </div><br/>
     
      <div class="col-md-12">
        <%= f.submit 'Atualizar', class: 'btn btn-success' %>
        <%= link_to 'Voltar', brands_path, class: 'btn btn-default' %>
      </div>
    </div> 
  <% end %>
</div>

app/views/brands/index.html.erb
<div class="container">
  <h1><span class="glyphicon glyphicon-list-alt"> Marcas </span></h1>
  <table class="table">
    <tr>
      <th>Nome</th>
      <th>Visualizar</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
   
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Visualizar', brand_path(brand), class: 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_brand_path(brand), class: 'btn btn-default' %></td>
        <td><%= link_to 'Deletar', brand_path(brand), method: :delete,
                data: { confirm: 'Tem certeza que quer deletar esta marca?' }, 
                class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table><br/>
  <hr/>
  <%= link_to 'Cadastrar Nova Marca', new_brand_path, class: 'btn btn-primary' %>
  <%= link_to 'Voltar', home_index_path, class: 'btn btn-default' %>
</div>

app/views/brands/new.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-user"> Nova Marca </span></h1>
  <%= form_for :brand, url: brands_path, class: 'form' do |f| %>
  <% if @brand.errors.any? %>
    <div class= "alert alert-danger" id="error_explanation">
      <ul>
        <h2>
          Ops!
        </h2>
        <% @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-md-12">  
      <%= f.label 'Nome' %><br>
      <div class="col-md-4">
        <%= f.text_field :name , class: 'form-control'%>
      </div>
    </div><br/>
   
    <div class="col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-success' %>
      <%= link_to 'Voltar', brands_path, class: 'btn btn-default' %>
    </div>
  </div>
  <% end %>
</div>

app/views/brands/show.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-zoom-in"> 
  Marca: <%=@brand.name%> </span></h1>
    <div>
      <label>Nome:</label>
      <%= @brand.name %>
    </div>
  <%= link_to 'Voltar', brands_path, class: 'btn btn-default' %>
</div>

app/views/clients/edit.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-edit"> 
  Editar Cliente </span></h1>
  <%= form_for :client, url: client_path(@client), method: :patch do |f| %>
    <% if @client.errors.any? %>
      <div class= "alert alert-danger" id="error_explanation">
        <ul>
          <h2>
            Ops!
          </h2>
          <% @client.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-md-12">  
        <%= f.label 'Nome' %><br>
        <div class="col-md-4">
          <%= f.text_field :name , class: 'form-control'%>
        </div>
      </div>
     
      <div class="col-md-12">
        <%= f.label 'Endereço' %><br>
        <div class="col-md-4">
        <%= f.text_area :address, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-12"><br/>
        <%= f.label 'Telefone' %><br>
        <div class="col-md-4">
          <%= f.text_field :tel, class: 'form-control' %>
        </div>
      </div><br/>
     
      <div class="col-md-12">
        <%= f.submit 'Atualizar', class: 'btn btn-success' %>
        <%= link_to 'Voltar', clients_path, class: 'btn btn-default' %>
      </div>
    </div> 
  <% end %>
</div>

app/views/clients/index.html.erb
<div class="container">
  <h1><span class="glyphicon glyphicon-list-alt"> Clientes </span></h1>
  <table class="table">
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Telefone</th>
      <th>Visualizar</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
   
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.address %></td>
        <td><%= client.tel %></td>
        <td><%= link_to 'Visualizar', client_path(client), class: 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_client_path(client), class: 'btn btn-default' %></td>
        <td><%= link_to 'Deletar', client_path(client), method: :delete,
                        data: { confirm: 'Tem certeza que quer deletar este cliente?' }, 
                        class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table><br/>
  <hr/>
  <%= link_to 'Cadastrar Novo Cliente', new_client_path, class: 'btn btn-primary' %>
  <%= link_to 'Voltar', home_index_path, class: 'btn btn-default' %>
</div>

app/views/clients/new.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-user"> Novo Cliente </span></h1>
  <%= form_for :client, url: clients_path, class: 'form' do |f| %>
  <% if @client.errors.any? %>
    <div class= "alert alert-danger" id="error_explanation">
      <ul>
        <h2>
          Ops!
        </h2>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-md-12">  
      <%= f.label 'Nome' %><br>
      <div class="col-md-4">
        <%= f.text_field :name , class: 'form-control'%>
      </div>
    </div>
   
    <div class="col-md-12">
      <%= f.label 'Endereço' %><br>
      <div class="col-md-4">
      <%= f.text_area :address, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12"><br/>
      <%= f.label 'Telefone' %><br>
      <div class="col-md-4">
        <%= f.text_field :tel, class: 'form-control' %>
      </div>
    </div><br/>
   
    <div class="col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-success' %>
      <%= link_to 'Voltar', clients_path, class: 'btn btn-default' %>
    </div>
  </div>
  <% end %>
</div>

app/views/clients/show.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-zoom-in"> 
  Cliente: <%=@client.name%> </span></h1>
    <div>
    	<label>Nome:</label>
    	<%= @client.name %>
    </div>
    <div>
    	<label>Endereço:</label>
    	<%= @client.address %>
    </div>
    <div>
    	<label>Telefone:</label>
    	<%= @client.tel %>
    </div>
  <%= link_to 'Voltar', clients_path, class: 'btn btn-default' %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="container">
    <div class="alert alert-info">
      <%= image_tag("simplify.gif", size: '150x100', class: 'pull-right') %>
		  <h1 style="color: #fff; margin-left: 450px">Águas D'itália</h1>
      <p align="left">
        <% if current_user %>
          <b style="color: #fff">Logado como <u><%= current_user.name %></u> | <%= link_to "Sair", '/sair', style: 'color: #fff' %></b>
        <% else %>
          <b style="color: #fff"><%= link_to 'Entrar', root_path %> | <%= link_to 'Cadastre-se', '/cadastrar' %></b>
        <% end %>
      </p>
    </div>
    <div align="center" class="col-md-12">
      <div class="col-md-3">
        <h2>Clientes</h2>
        <%= link_to "Ver Clientes", clients_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3">
        <h2>Produtos</h2>
        <%= link_to "Ver Produtos", products_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3">
        <h2>Marcas</h2>
        <%= link_to "Ver Marcas", brands_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3">
        <h2>Pedidos</h2>
        <%= link_to "Ver Pedidos", orders_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <h1><span class="glyphicon glyphicon-list-alt"> Pedidos </span></h1>
  <table class="table">
    <tr>
      <th>Nº do Pedido</th>
      <th>Data do Pedido</th>
      <th>Nome do produto</th>
      <th>Quantidade</th>
      <th>Valor</th>
      <th>Visualizar</th>
      <th>Deletar</th>
    </tr>
   
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.date %></td>
        <td><%= order.product ? order.product.name : 'pedido via api' %></td>
        <td><%= order.quantity %></td>
        <td><%= order.value %></td>
        <td><%= link_to 'Visualizar', order_path(order), class: 'btn btn-default' %></td>
        <td><%= link_to 'Deletar', order_path(order), method: :delete,
                data: { confirm: 'Tem certeza que quer deletar esta marca?' }, 
                class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table><br/>
  <hr/>
  <%= link_to 'Cadastrar Novo Pedido', new_order_path, class: 'btn btn-primary' %>
  <%= link_to 'Voltar', home_index_path, class: 'btn btn-default' %>
  <%= link_to 'Exportar para Excel', orders_path(format: :xlsx), class: 'btn btn-success pull-right' %>
</div>

app/views/orders/new.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-tag"> Novo Pedido </span></h1>
  <%= form_for :order, url: orders_path, class: 'form' do |f| %>
  <% if @order.errors.any? %>
    <div class= "alert alert-danger" id="error_explanation">
      <ul>
        <h2>
          Ops!
        </h2>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-md-12">  
      <%= f.label 'Data do pedido' %><br>
      <div class="col-md-4">
        <%= f.text_field :date , class: 'form-control'%>
      </div>
    </div>
   
    <div class="col-md-12">
      <%= f.label 'Quantidade do Pedido' %><br>
      <div class="col-md-4">
      <%= f.text_field :quantity, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12"><br/>
      <%= f.label 'Valor do Pedido' %><br>
      <div class="col-md-4">
        <%= f.text_field :value, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12"><br/>
      <%= f.label 'Nome do Produto' %><br>
      <div class="col-md-4">
       <select name="produto" class="form-control">
          <% products = Product.all %>
          <% products.each do |product| %>
            <option value="<%= product.id %>"><%= product.name %></option>
          <% end %>
       </select>
      </div>
    </div><br/>
   
    <div class="col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-success' %>
      <%= link_to 'Voltar', orders_path, class: 'btn btn-default' %>
    </div>
  </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-zoom-in"> 
  Pedido: <%=@order.id%> </span></h1>
    <div>
      <label>Data:</label>
      <%= @order.date %>
    </div>
    <div>
      <label>Quantidade:</label>
      <%= @order.quantity %>
    </div>
    <div>
      <label>Valor:</label>
      <%= @order.value %>
    </div>
  <%= link_to 'Voltar', orders_path, class: 'btn btn-default' %>
</div>

app/views/products/edit.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-edit"> 
  Editar Produto </span></h1>
  <%= form_for :product, url: product_path(@product), method: :put do |f| %>
    <% if @product.errors.any? %>
      <div class= "alert alert-danger" id="error_explanation">
        <ul>
          <h2>
            Ops!
          </h2>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-md-12">  
        <%= f.label 'Nome do Produto' %><br>
        <div class="col-md-4">
          <%= f.text_field :name , class: 'form-control'%>
        </div>
      </div>
     
      <div class="col-md-12">
        <%= f.label 'Quantidade do Produto' %><br>
        <div class="col-md-4">
        <%= f.text_field :quantity, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-12"><br/>
        <%= f.label 'Preço do Produto' %><br>
        <div class="col-md-4">
          <%= f.text_field :price, class: 'form-control' %>
        </div>
      </div>

     <div class="col-md-12"><br/>
      <%= f.label 'Marca do Produto' %><br>
      <div class="col-md-4">
        <%= select_tag 'brands', (options_for_select(@brands.collect{|b| [b.name, b.id]}, 
                        selected: @product.brand.id)), class: 'form-control' %>
      </div>
    </div><br/>
     
      <div class="col-md-12">
        <%= f.submit 'Atualizar', class: 'btn btn-success' %>
        <%= link_to 'Voltar', products_path, class: 'btn btn-default' %>
      </div>
    </div> 
  <% end %>
</div>

app/views/products/index.html.erb
<div class="container">
  <h1><span class="glyphicon glyphicon-list-alt"> Produtos </span></h1>
  <table class="table">
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Preço</th>
      <th>Marca</th>
      <th>Visualizar</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
   
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.quantity %></td>
        <td><%= number_with_precision(product.price, precision: 2) %></td>
        <td>
          <%= product.brand ? product.brand.name : 'marca via api' %> 
        </td>
        <td><%= link_to 'Visualizar', product_path(product), class: 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_product_path(product), class: 'btn btn-default' %></td>
        <td><%= link_to 'Deletar', product_path(product), method: :delete,
                        data: { confirm: 'Tem certeza que quer deletar este produto?' }, 
                        class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table><br/>
  <hr/>
  <%= link_to 'Cadastrar Novo Produto', new_product_path, class: 'btn btn-primary' %>
  <%= link_to 'Voltar', home_index_path, class: 'btn btn-default' %>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-tag"> Cadastre um Produto </span></h1>
  <%= form_for :product, url: products_path, class: 'form' do |f| %>
  <% if @product.errors.any? %>
    <div class= "alert alert-danger" id="error_explanation">
      <ul>
        <h2>
          Ops!
        </h2>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-md-12">  
      <%= f.label 'Nome do Produto' %><br>
      <div class="col-md-4">
        <%= f.text_field :name , class: 'form-control'%>
      </div>
    </div>
   
    <div class="col-md-12">
      <%= f.label 'Quantidade do Produto' %><br>
      <div class="col-md-4">
      <%= f.text_field :quantity, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12"><br/>
      <%= f.label 'Preço do Produto' %><br>
      <div class="col-md-4">
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12"><br/>
      <%= f.label 'Marca do Produto' %><br>
      <div class="col-md-4">
       <select name="marca" class="form-control">
          <% brands = Brand.all %>
          <% brands.each do |brand| %>
            <option value="<%= brand.id %>"><%= brand.name %></option>
          <% end %>
       </select>
      </div>
    </div><br/>
   
    <div class="col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-success' %>
      <%= link_to 'Voltar', products_path, class: 'btn btn-default' %>
    </div>
  </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-zoom-in"> 
  Produto: <%=@product.name%> </span></h1>
    <div>
    	<label>Nome:</label>
    	<%= @product.name %>
    </div>
    <div>
    	<label>Quantidade:</label>
    	<%= @product.quantity %>
    </div>
    <div>
    	<label>Preço:</label>
    	<%= number_with_precision(@product.price, precision: 2) %>
    </div>
    <div>
      <label>Marca:</label>
      <%= @product.brand ? @product.brand.name : 'marca via api' %>
    </div>
  <%= link_to 'Voltar', products_path, class: 'btn btn-default' %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="page-header"><span class="glyphicon glyphicon-user"> Cadastro </span></h1>
  <%= form_for :user, url: '/users' do |f| %>
    <div class="form-group">
      <div class="col-md-12">  
        <%= f.label 'Nome' %><br>
        <div class="col-md-4">
          <%= f.text_field :name , class: 'form-control'%>
        </div>
      </div>
     
      <div class="col-md-12">
        <%= f.label 'Email' %><br>
        <div class="col-md-4">
        <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-12"><br/>
        <%= f.label 'Senha' %><br>
        <div class="col-md-4">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-12"><br/>
        <%= f.label 'Confirme a Senha' %><br>
        <div class="col-md-4">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div><br/>
     
      <div class="col-md-12">
        <%= f.submit 'Cadastrar', class: 'btn btn-success' %>
        <%= link_to 'Voltar', entrar_path, class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>